apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
  - image: dani100/client
    context: client
    sync:
      manual:
      - src: src/**/*.js
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: dani100/comments
    context: comments
    sync:
      manual:
      - src: /*.js
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: dani100/posts
    context: posts
    sync:
      manual:
      - src: /*.js
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: dani100/event-bus
    context: event-bus
    sync:
      manual:
      - src: /*.js
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: dani100/query
    context: query
    sync:
      manual:
      - src: /*.js
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: dani100/moderation
    context: moderation
    sync:
      manual:
      - src: /*.js
        dest: .
    docker:
      dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
  - ./infra/k8s/*
deploy:
  kubectl: {}