apiVersion: apps/v1 # Specify the deployment version and pods in in v1
kind: Deployment # specify the purpose of the configuration
metadata: 
  name: event-bus-depl # name of the deployment
spec: # specify how this deployment should behave
  replicas: 1
  selector: 
    matchLabels:
      app: event-bus
  template: 
    metadata: 
      labels: 
        app: event-bus
    spec: 
      containers: 
        - name: event-bus
          image: dani100/event-bus
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata: 
  name: event-bus-srv
spec: 
  selector: 
    app: event-bus
  type: ClusterIP
  ports: 
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005