apiVersion: apps/v1 # Specify the deployment version and pods in in v1
kind: Deployment # specify the purpose of the configuration
metadata: 
  name: posts-depl # name of the deployment
spec: # specify how this deployment should behave
  replicas: 1
  selector: 
    matchLabels:
      app: posts
  template: 
    metadata: 
      labels: 
        app: posts
    spec: 
      containers: 
        - name: posts
          image: dani100/posts
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata: 
  name: posts-clusterip-srv
spec: 
  selector: 
    app: posts
  type: ClusterIP
  ports: 
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000