apiVersion: apps/v1 # Specify the deployment version and pods in in v1
kind: Deployment # specify the purpose of the configuration
metadata: 
  name: query-depl # name of the deployment
spec: # specify how this deployment should behave
  replicas: 1
  selector: 
    matchLabels:
      app: query
  template: 
    metadata: 
      labels: 
        app: query
    spec: 
      containers: 
        - name: query
          image: dani100/query
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata: 
  name: query-srv
spec: 
  selector: 
    app: query
  type: ClusterIP
  ports: 
    - name: query
      protocol: TCP
      port: 4002
      targetPort: 4002